package com.example.client;

import com.example.interfaces.ICabinet;
import com.example.interfaces.VetObserver;
import com.example.models.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Cabinet extends JFrame {

    private static final Logger logger = Logger.getLogger(Cabinet.class.getName());

    public final ICabinet cabinetService;
    public Cabinet(ICabinet cabinetService) {
        this.cabinetService = cabinetService;
        initComponents();
        try {
            VetObserver observer = new VetObserverImpl(this, jButton1);
            cabinetService.registerObserver(observer);
        } catch (RemoteException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erreur lors de l'enregistrement de l'observer : " + e.getMessage(),
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jPanel3 = new JPanel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jPanel4 = new JPanel();
        jLabel3 = new JLabel();
        NomAnimal = new JTextField();
        NomMaitre = new JTextField();
        Race = new JTextField();
        jLabel8 = new JLabel();
        Espece = new JComboBox<>();
        jButton1 = new JButton();
        jButton5 = new JButton();
        jButton6 = new JButton();
        jButton7 = new JButton();
        Cree = new JRadioButton();
        Traite = new JRadioButton();
        Encours = new JRadioButton();
        jLabel9 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new Color(204, 204, 204));

        jLabel1.setBackground(new Color(102, 102, 102));
        jLabel1.setFont(new Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("              Cabinet Vétérinaire");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 604, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.png")));


        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap())
        );

        jLabel4.setFont(new Font("Liberation Sans", 2, 18)); // NOI18N
        jLabel4.setText("Nom Animal:");

        jLabel5.setFont(new Font("Liberation Sans", 2, 18)); // NOI18N
        jLabel5.setText("Nom Maitre:");

        jLabel6.setFont(new Font("Liberation Sans", 2, 18)); // NOI18N
        jLabel6.setText("Race:");

        jLabel7.setFont(new Font("Liberation Sans", 2, 18)); // NOI18N
        jLabel7.setText("Espéce:");

        jPanel4.setBackground(new Color(204, 204, 204));
        jPanel4.setForeground(new Color(204, 204, 204));

        jLabel3.setFont(new Font("Liberation Sans", 3, 24)); // NOI18N
        jLabel3.setText("Formulaire d'Enregistrement");

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 395, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)
                                .addContainerGap(17, Short.MAX_VALUE))
        );


        jLabel8.setFont(new Font("Liberation Sans", 2, 18)); // NOI18N
        jLabel8.setText("Etat Dossier:");

        Espece.setModel(new DefaultComboBoxModel<>(new String[] { "Chien", "Chat", "Oiseau"}));

        jButton1.setBackground(new Color(153, 153, 153));
        jButton1.setFont(new Font("Liberation Sans", 1, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new Color(153, 153, 153));
        jButton5.setFont(new Font("Liberation Sans", 1, 12)); // NOI18N
        jButton5.setText("Supprimer");
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton6.setBackground(new Color(153, 153, 153));
        jButton6.setFont(new Font("Liberation Sans", 1, 12)); // NOI18N
        jButton6.setText("Maj Etat");
        jButton6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                    jButton6ActionPerformed(evt);

            }
        });

        jButton7.setBackground(new Color(153, 153, 153));
        jButton7.setFont(new Font("Liberation Sans", 1, 12)); // NOI18N
        jButton7.setText("Mettre à jour");
        jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Cree.setText(Etat.CREE.getValue());
        Encours.setText(Etat.EN_COURS.getValue());
        Traite.setText(Etat.TRAITE.getValue());

        ButtonGroup etatGroup = new ButtonGroup();
        etatGroup.add(Cree);
        etatGroup.add(Encours);
        etatGroup.add(Traite);
        Cree.setSelected(true);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(11, 11, 11))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(NomMaitre, GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(NomAnimal, GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(Race)
                                                                        .addComponent(Espece, 0, 171, Short.MAX_VALUE)))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(Cree, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(Encours, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(Traite, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)))))
                                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(jLabel4))
                                                                        .addComponent(NomAnimal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGap(64, 64, 64)
                                                                                .addComponent(jLabel5))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGap(52, 52, 52)
                                                                                .addComponent(NomMaitre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(56, 56, 56)
                                                                .addComponent(jLabel6))
                                                        .addComponent(Race, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(51, 51, 51)
                                                .addComponent(jLabel7))
                                        .addComponent(Espece, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(Cree)
                                        .addComponent(Traite)
                                        .addComponent(Encours))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
        );

        jLabel9.setFont(new Font("Liberation Sans", 3, 18)); // NOI18N
        jLabel9.setText("Listes Des Animaux:");

        jTable1.setBackground(new Color(204, 204, 204));
        jTable1.setModel(new DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                },
                new String [] {
                        "Nom Animal", "Nom Maitre", "Race", "Espece", "Etat Dossier"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 299, GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 481, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(14, 14, 14))))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 259, GroupLayout.PREFERRED_SIZE)
                                                .addGap(195, 195, 195))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(26, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>

    //  Bouton Ajouter
    private void jButton1ActionPerformed(ActionEvent evt) {
        try {
            String nomAnimal = NomAnimal.getText().trim();
            String maitreAnimal = NomMaitre.getText().trim();
            String raceAnimal = Race.getText().trim();
            String espece = (String) Espece.getSelectedItem();

            if (nomAnimal.isEmpty() || maitreAnimal.isEmpty() || raceAnimal.isEmpty() || espece == null) {
                JOptionPane.showMessageDialog(this,
                        "Veuillez remplir tous les champs.",
                        "Champs manquants",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            String etatDossier = "";
            if (Cree.isSelected()) {
                etatDossier = Etat.CREE.getValue();
            } else if (Encours.isSelected()) {
                etatDossier = Etat.EN_COURS.getValue();
            } else if (Traite.isSelected()) {
                etatDossier = Etat.TRAITE.getValue();
            }
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            //for (int i = 1; i <= 10; i++) {
                String nom = nomAnimal ;
                String maitre = maitreAnimal;
                String race = raceAnimal;
                String etat = etatDossier;
                AnimalDTO animalDTO= null;
                if ("Chien".equalsIgnoreCase(espece)) {
                    animalDTO = cabinetService.addAnimal(nom, maitre, race, new Chien());
                } else if ("Chat".equalsIgnoreCase(espece)) {
                    animalDTO =  cabinetService.addAnimal(nom, maitre, race, new Chat());
                } else if ("Oiseau".equalsIgnoreCase(espece)) {
                    animalDTO =  cabinetService.addAnimal(nom, maitre, race, new Oiseau());
                }

                if (animalDTO != null) {
                    model.insertRow(0, new Object[]{nom, maitre, race, espece, etat});
                }

                JOptionPane.showMessageDialog(this,
                    "L’animal " + nom + " a bien été ajoutéé.",
                    "Mise à jour réussie",
                    JOptionPane.INFORMATION_MESSAGE);

                int size = cabinetService.sizeAnimal();

                // Vérifier le seuil côté client
                if (size == 50 || size == 100 ) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Seuil de  animaux atteint "+ size,
                            "ALERTE CABINET",
                            JOptionPane.WARNING_MESSAGE
                    );
                }
            //}

         clearForm();

        } catch (RemoteException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erreur lors de l'ajout de l'animal : " + ex.getMessage(),
                    "Erreur RMI",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    //  Bouton Mise à Jour
    private void jButton7ActionPerformed(ActionEvent evt) {
        String nomFiled = NomAnimal.getText().trim();

        if (nomFiled.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez entrer le nom de l’animal à modifier.",
                    "Champ vide",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }


        String maitreField = NomMaitre.getText().trim();
        String raceField = Race.getText().trim();
        String espece = (String) Espece.getSelectedItem();

        if (maitreField.isEmpty() || raceField.isEmpty() || espece == null) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez remplir tous les champs pour la modification.",
                    "Champs manquants",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Espece especeObj = null;
            if ("Chien".equalsIgnoreCase(espece)) {
                especeObj = new Chien();
            } else if ("Chat".equalsIgnoreCase(espece)) {
                especeObj = new Chat();
            } else if ("Oiseau".equalsIgnoreCase(espece)) {
                especeObj = new Oiseau();
            }

            AnimalDTO updatedAnimal = new AnimalDTO(nomFiled, maitreField, raceField, especeObj);
            try {
                cabinetService.updateAnimal(nomFiled, updatedAnimal);
            } catch (RemoteException e) {
                JOptionPane.showMessageDialog(this,
                        "L’animal " + nomFiled + " n'existe pas",
                        "Veuillez saisir un animal deja existant",
                        JOptionPane.ERROR_MESSAGE);

                clearForm();
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).equals(nomFiled)) {
                    model.setValueAt(maitreField, i, 1);
                    model.setValueAt(raceField, i, 2);
                    model.setValueAt(espece, i, 3);
                    break;
                }
            }

            clearForm();
            JOptionPane.showMessageDialog(this,
                    "L’animal " + nomFiled + " a bien été modifié.",
                    "Mise à jour réussie",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (RemoteException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erreur lors de la mise à jour : " + ex.getMessage(),
                    "Erreur RMI",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Bouton Supprimer
    private void jButton5ActionPerformed(ActionEvent evt) {
        String nom = NomAnimal.getText().trim();

        if (nom.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez entrer le nom de l’animal à supprimer.",
                    "Champ vide",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            cabinetService.removeAnimal(nom);

            // Mise à jour du tableau
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).equals(nom)) {
                    model.removeRow(i);
                    break;
                }
            }
            // Message de confirmation
            JOptionPane.showMessageDialog(this,
                    "L’animal " + nom + " a bien été supprimé.",
                    "Suppression réussie",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this,
                    "Erreur lors de la suppression : " + ex.getMessage(),
                    "Erreur RMI",
                    JOptionPane.ERROR_MESSAGE);
        }
        clearForm();
    }


    private void jButton6ActionPerformed(ActionEvent evt) {

        String nomFiled = NomAnimal.getText().trim();



        if (nomFiled.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez entrer le nom de l’animal à modifier.",
                    "Champ vide",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Etat nouvelEtat = null;
        if (Cree.isSelected()) {
            nouvelEtat = Etat.CREE;
        } else if (Encours.isSelected()) {
            nouvelEtat = Etat.EN_COURS;
        } else if (Traite.isSelected()) {
            nouvelEtat = Etat.TRAITE;
        }

        try {
            cabinetService.setEtatAnimal(nomFiled, nouvelEtat);
            JOptionPane.showMessageDialog(this, "État du dossier mis à jour avec succès !");

        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this,
                    "L’animal " + nomFiled + " n'existe pas",
                    "Veuillez saisir un animal deja existant",
                    JOptionPane.ERROR_MESSAGE);

            clearForm();
            return;
        }

             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             for (int i = 0; i < model.getRowCount(); i++) {
                String nomAnimal = (String) model.getValueAt(i, 0); // colonne 0 = nom
                 if (nomAnimal.equalsIgnoreCase(nomFiled)) {
                model.setValueAt(nouvelEtat.getValue(), i, 4); // colonne 4 = état
                break; // on a trouvé la ligne, plus besoin de continuer
            }
        }
             clearForm();
    }

    // clear formulaire
    private void clearForm() {
        NomAnimal.setText("");
        NomAnimal.setText("");
        NomMaitre.setText("");
        Race.setText("");
        Espece.setSelectedIndex(0);
        Cree.setSelected(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(() -> new Cabinet().setVisible(true));
    }

    // Variables declaration - do not modify
    private JRadioButton Cree;
    private JRadioButton Encours;
    private JComboBox<String> Espece;
    private JTextField NomAnimal;
    private JTextField NomMaitre;
    private JTextField Race;
    private JRadioButton Traite;
    private JButton jButton1;
    private JButton jButton5;
    private JButton jButton6;
    private JButton jButton7;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    // End of variables declaration
}